# general
device: cuda
seed: 3008

# model
model: unet
model_file: ckpts/600nm_mmff_model.pt
mm_model_file: Null
shallow: 0
class_num: 4
bg_opt: False

# dataset
data_path: NPP_23.05.2025/
loc_dir: /home/chris/Datasets/03_HORAO/${data_path}
data_dir: ${loc_dir}
k_select: 0
cases: ['val2_600_b_npp_ht_tumor.txt', 'k1_600_b_npp_ht_tumor_imbalance.txt', 'k2_600_b_npp_ht_tumor_imbalance.txt', 'k3_600_b_npp_ht_tumor_imbalance.txt']

# mueller matrix parameters
norm_opt: 1
levels: 0
ochs: 10
kernel_size: 0
activation: Null
method: pooling
feature_keys:
  - intensity
  - azimuth
  - totp
  - linr
  - datt
wlens:
  - 600

