# general
device: cuda
logging: 1
model: unet
levels: 1
model_file: comic-flower-3_ckpt_epoch147.pt
batch_size: 1

# augmentation settings
flips: False
rotation: 0
shuffle_crop: 0
noise: 0
gamma: 0

# dataset
#cases: ['test_tumor_grade4_npp.txt', 'test_tumor_grade3_npp.txt', 'test_tumor_grade2_npp.txt']
cases: ['experiment_1_550.txt']
data_path: NPP/
ubx_dir: /storage/homefs/db09h030/masterthesis/polarimetric/data/${data_path}
data_dir: ${ubx_dir}
class_num: 4
bg_opt: False
wlens:
  - 550