# general
device: cpu
logging: 0
model: unet
levels: 1
model_file: best_lc_model.pt
batch_size: 1

# augmentation settings
flips: False
rotation: 0
shuffle_crop: 0
noise: 0
gamma: 0

# dataset
#cases: ['test_tumor_grade4_npp.txt', 'test_tumor_grade3_npp.txt', 'test_tumor_grade2_npp.txt']
cases: ['k1_600_npp_imbalance.txt']
class_num: 4
bg_opt: False
wlens:
  - 600