# general
logging: 1
model: unet
levels: 0
model_file: usual-snowflake-4240_ckpt_epoch118.pt
batch_size: 1

# augmentation settings
flips: False
rotation: 0
shuffle_crop: 0
noise: 0
gamma: 0

# dataset
cases: ['test_tumor_grade4_npp.txt', 'test_tumor_grade3_npp.txt', 'test_tumor_grade2_npp.txt']
class_num: 4
bg_opt: False