# general
logging: 1
model: linr
levels: 1
model_file: Null
batch_size: 1

# augmentation settings
flips: False
perspective: 0
elastic: 0
rotation: 0
crop: 0
shuffle_crop: 0

# dataset
cases: ['k1_c_imbalance.txt', 'k2_c_imbalance.txt', 'k3_c_imbalance.txt']
class_num: 2
bg_opt: False

# mueller matrix parameters
kernel_size: 0
activation: Null
method: pooling
feature_keys:
  - linr
wlens:
  - 550
