# general
device: cuda
logging: 0
seed: 3008

# model
model: unet
model_file: Null
mm_model_file: Null
shallow: 0

# training
batch_size: 2
lr: 1e-4
epochs: 200
weight_decay: 1e-8
val_fraction: 0.1
amp: False
bg_opt: False
labeled_only: True
group: Null
class_num: 4

# dataset paths
data_path: TumorMeasurementsCalib/
ubx_dir: /storage/homefs/ch21z139/01_datasets/${data_path}
usb_dir: /media/chris/EB62-383C/${data_path}
loc_dir: /home/chris/Datasets/data/${data_path}
map_dir: Null
data_dir: ${loc_dir}
data_subfolder: raw_data
k_select: 0
imbalance: True

# mueller matrix parameters
levels: 1
kernel_size: 0
activation: Null
method: pooling
feature_keys:
  - intensity
#  - azimuth
  - std
  - totp
  - linr
wlens:
  - 550

# augmentation settings
crop: 0
flips: False
rotation: 0
shuffle_crop: 0
