# general
device: cuda
logging: 0
seed: 3008

# model
model: unet
model_file: Null
mm_model_file: Null
shallow: 0

# training
batch_size: 2
lr: 1e-4
epochs: 200
weight_decay: 1e-8
bg_opt: False
labeled_only: True
group: Null
class_num: 4
num_workers: 4
patience: Null
alpha: 0.25

# dataset
data_path: NPP/
ubx_dir: /storage/homefs/ch21z139/01_datasets/${data_path}
usb_dir: /media/chris/EB62-383C/${data_path}
loc_dir: /home/chris/Datasets/03_HORAO/${data_path}
map_dir: Null
data_dir: ${loc_dir}
data_subfolder: raw_data
k_select: 0
imbalance: False
cases: ['val2_b_npp_infiltrate.txt', 'k1_b_npp_infiltrate.txt', 'k2_b_npp_infiltrate.txt', 'k3_b_npp_infiltrate.txt']
infill: 1

# mueller matrix parameters
norm_opt: 1
levels: 0
ochs: 10
kernel_size: 0
activation: Null
method: pooling
feature_keys:
  - intensity
  - azimuth
  - totp
  - linr
  - datt
  - mask
wlens:
  - 550

# augmentation settings
flips: 1
rotation: 45
shuffle_crop: 0
noise: 0
gamma: 0
